### ISSUE TITLE
Changing src attribute when is="x-frame-bypass" is set

### ISSUE THREAD

**Issue by ttomovcik** [niutech/x-frame-bypass#2]
Hi. I'm making an PWA which will change the URLs dynamically and thanks to your amazing work I can load external sites. But after setting that is="x-fr..." attribute, I'm no longer able to change the src attribute. 

Is there a way to change the url dynamically and still keep the is="x-frame-bypass" attr set?

**Comment by niutech** [comment]
Yes, by implementing `attributeChangedCallback()` event. This could be addressed in the next version.

**Comment by ttomovcik** [comment]
@niutech Thanks. Looking forward to it 👍. Modified my code to use cors.io for now 😊

**Comment by Slluxx** [comment]
you could just rewrite the innerHTML like this

`container.innerHTML = '<iframe src="' + url +'" is="x-frame-bypass"></iframe>';`

**Comment by ttomovcik** [comment]
> you could just rewrite the innerHTML like this
> 
> `container.innerHTML = '<iframe src="' + url +'" is="x-frame-bypass"></iframe>';`

I'll give it a shot and update soon. Thank you for the suggestion.

**Comment by PandaWhoCodes** [comment]
The above worked for me

**Comment by erikgelfat** [comment]
@niutech how can I implement the `attributeChangedCallback()` event?

**Comment by niutech** [comment]
It's just been fixed, now changing the `src` attribute works.
