### ISSUE TITLE
it's work not with Facebook

### ISSUE THREAD

**Issue by lokutus24** [niutech/x-frame-bypass#20]
Access to fetch at  from origin 'https://xy' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by E3V3A** [comment]
How to fix? I don't understand your post...

**Comment by niutech** [comment]
I checked it, www.facebook.com works in `x-frame-bypass`.

**Comment by lokutus24** [comment]
yes, it works, but it does not see, then i'm logged in.
