### ISSUE TITLE
Set user agent?

### ISSUE THREAD

**Issue by edent** [niutech/x-frame-bypass#23]
When trying to access Twitter, I get this error:

> This is the legacy version of twitter.com. We will be shutting it down on 1st June, 2020. Please switch to a supported browser, or disable the extension which masks your browser. You can see a list of supported browsers in our Help Center.

Is there any way to set a UA string?

**Comment by niutech** [comment]
No, it uses the user agent string of your web browser. But you can override it using the User Agent Switcher extension.
