### ISSUE TITLE
Doesn't work with Quora

### ISSUE THREAD

**Issue by xjdeng** [niutech/x-frame-bypass#30]
Am I using it correctly?  This works for many sites, but unfortunately, it doesn't with Quora.

Try copying and pasting the following into an HTML file:

```
<html>
<script type="module" src="https://unpkg.com/x-frame-bypass"></script>
<iframe name="Framename" sandbox="allow-forms allow-scripts" is="x-frame-bypass" src="https://www.quora.com/Why-don-t-people-take-INTJ-advice" frameborder="0" style="width: 100%; height: 500px;"> </iframe>
</html>

```

**Comment by niutech** [comment]
It works for me:
![Quora](https://user-images.githubusercontent.com/384997/102688407-c9e63680-41f6-11eb-8084-faea0b42cc6f.png)

That said, it reloads after a while. This is due to some JS code on that page, which I cannot modify.
