### ISSUE TITLE
run action on src change, get src

### ISSUE THREAD

**Issue by xanman12321** [niutech/x-frame-bypass#5]
Is there a way to obtain the "internal" source? Sorry if this doesn't belong here, I'm relatively new to Github.

**Comment by ttomovcik** [comment]
You can view the source here

> https://github.com/niutech/x-frame-bypass/blob/master/x-frame-bypass.js

**Comment by xanman12321** [comment]
No, sorry, I meant the source of the webpage.

**Comment by ttomovcik** [comment]
@xanman12321 Like the URL of the loaded website inside of the iframe?

**Comment by niutech** [comment]
You can see the `<x-frame-bypass>` document source by right-clicking inside it and selecting `Inspect element` from the context menu.
