### ISSUE TITLE
Doesn't work in Chrome extensions

### ISSUE THREAD

**Issue by thdoan** [niutech/x-frame-bypass#51]
I tried to load https://news.ycombinator.com/ into a simple extensions popup, but got this error:

![image](https://user-images.githubusercontent.com/4110567/218864129-98a7c9c9-06fd-404d-9967-4ab21d47dfac.png)

![image](https://user-images.githubusercontent.com/4110567/218864335-265e09e5-a2d4-4a45-ac7c-92dc71d3bcf2.png)

![image](https://user-images.githubusercontent.com/4110567/218864407-3eb8bc79-9eb5-43fe-9ded-6b631547fb9e.png)

![image](https://user-images.githubusercontent.com/4110567/218864493-c371ab19-4e5c-4db5-85d7-ae168e042f44.png)

![image](https://user-images.githubusercontent.com/4110567/218864556-0506021f-e933-4e7c-9b9b-354036ee57eb.png)

**Comment by Boot-Now** [comment]
You need the other party to grant the operation permission for the access
to work

Vào 04:14, T.4, 15 Th2, 2023 T. H. Doan ***@***.***> đã viết:

**Comment by thdoan** [comment]
@Boot-Now, I do not have control over hackernews. I thought we could use this package to "bypass the X-Frame-Options: deny/sameorigin response header".

**Comment by Boot-Now** [comment]
You from Vietnamese or where ?

Vào 06:47, T.4, 15 Th2, 2023 T. H. Doan ***@***.***> đã viết:

**Comment by ShaneOss** [comment]
You can create your own proxy on Cloudflare by setting up a worker and using the source below.
https://github.com/Zibri/cloudflare-cors-anywhere

**Comment by Boot-Now** [comment]
Wow, you great !

Vào 06:51, T.4, 15 Th2, 2023 Shane ***@***.***> đã viết:

**Comment by thdoan** [comment]
@ShaneOss Let me try to set one up now -- I've never done this before.

**Comment by Boot-Now** [comment]
Ok, if you pecfect .

Vào 06:53, T.4, 15 Th2, 2023 T. H. Doan ***@***.***> đã viết:

**Comment by thdoan** [comment]
@ShaneOss I just created my cloudflare worker and updated `x-frame-bypass.js ` to point to my own worker, but the iframe is still not loading hackernews. Here's the error:

![image](https://user-images.githubusercontent.com/4110567/218893205-4ae1a030-9536-4bed-94da-5006e0167f49.png)

The only thing I changed in the worker code is this:

```
whitelist = ["https://www.hackernews.com/"]; // regexp for whitelisted origins
```

**Comment by thdoan** [comment]
Okay, I made some progress. After adding `host_permissions` required by extensions, I'm now getting this error:

![image](https://user-images.githubusercontent.com/4110567/218894515-f28e5834-bc3f-49c8-a102-8718f2027c59.png)

Is there some code I need to change in `x-frame-bypass.js` to make it work with the worker code at https://github.com/Zibri/cloudflare-cors-anywhere ?

**Comment by thdoan** [comment]
Debugging the issue in the cloudflare worker console, it seems there's an error in the https://github.com/Zibri/cloudflare-cors-anywhere code:

![image](https://user-images.githubusercontent.com/4110567/218895476-361e903a-018b-45f8-9b96-4017f939b049.png)

**Comment by ShaneOss** [comment]
> @ShaneOss I just created my cloudflare worker and updated `x-frame-bypass.js ` to point to my own worker, but the iframe is still not loading hackernews. Here's the error:
> 
> ![image](https://user-images.githubusercontent.com/4110567/218893205-4ae1a030-9536-4bed-94da-5006e0167f49.png)
> 
> The only thing I changed in the worker code is this:
> 
> ```
> whitelist = ["https://www.hackernews.com/"]; // regexp for whitelisted origins
> ```

My understanding is the whitelist is to only allow those domains to use your proxy. I.e. the domain you're calling from. Are you writing a plugin for www.hackersnews.com, and would be calling it from that domain? If not, I wouldn't specify one.

**Comment by thdoan** [comment]
Hey guys, I managed to solve all issues by using this worker instead :D - https://gist.github.com/Kahtaf/e20515800054efcfb22830b4bc883880

Thanks for your assist.
