### ISSUE TITLE
use in react app

### ISSUE THREAD

**Issue by ahmedsalihh** [niutech/x-frame-bypass#6]
Hello, forgive me if this is a noob question but how can i use this on react app ?

**Comment by clickclickonsal** [comment]
In the `index.html` add this `<script type="module" src="https://unpkg.com/x-frame-bypass"></script>` inside the head  tags.`<head></div>`.

Then to use it you can return and `iframe` with the ` is="x-frame-bypass"` prop. 😄 
Ex.
```js
render() {
  return (
    <iframe
        is="x-frame-bypass"
        src="https://dev.to/"
        height="100%"
        width-"100%"
     /> 
  );
}
```

**Comment by manal-t07** [comment]
Actually this is not working on my react app after this, still shows "refused to connect".
